version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iucnewsbackend
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/iuc_news_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_FORMAT_SQL: true
      HIKARI_MAX_POOL_SIZE: 10
      HIKARI_MIN_IDLE: 2
      HIKARI_IDLE_TIMEOUT: 30000
      HIKARI_CONN_TIMEOUT: 20000
      HIKARI_MAX_LIFETIME: 1800000
      LOGGING_HIBERNATE_SQL: DEBUG
      LOGGING_HIBERNATE_BINDER: TRACE
    depends_on:
      - database
    restart: always

  database:
    image: mysql:8.0
    container_name: iuc_news_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: iuc_news_db
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
